apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 0.13.12
      reconcileStrategy: ChartVersion
      sourceRef:
        name: metallb
        kind: HelmRepository
        namespace: flux-system
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
