apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  releaseName: kafka
  chart:
    spec:
      chart: kafka
      reconcileStrategy: ChartVersion
      sourceRef:
        name: bitnami
        kind: HelmRepository
        namespace: flux-system
      version: "19.1.0"
  interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka
  namespace: kafka
data:
  values.yaml: |
    brokers: 1
    cp-schema-registry:
      enabled: false
    cp-kafka-rest:
      enabled: false
    cp-kafka-connect:
      enabled: false
    cp-kafka-rest:
      enabled: false
    cp-ksql-server:
      enabled: false
    cp-control-center:
      enabled: false