apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dapr
spec:
  releaseName: dapr
  chart:
    spec:
      chart: dapr
      reconcileStrategy: ChartVersion
      sourceRef:
        name: dapr
        kind: HelmRepository
        namespace: flux-system
      version: "1.9.2"
  interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace