apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb
  namespace: cockroachdb
spec:
  releaseName: cockroachdb
  chart:
    spec:
      chart: cockroachdb
      reconcileStrategy: ChartVersion
      sourceRef:
        name: cockroachdb
        kind: HelmRepository
        namespace: flux-system
      version: "9.1.0"
  interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: cockroachdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cockroachdb
  namespace: cockroachdb
data:
  values.yaml: |
    conf:
      single-node: true
    statefulset: 
      replicas: 1

