apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  values.yaml: |
    controller:
      pod:
        annotations:
          dapr.io/enabled: "true"
          dapr.io/app-id: nginx
          dapr.io/app-port: "80"
          dapr.io/sidecar-listen-addresses: "[::],0.0.0.0"