apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-system
spec:
  releaseName: default
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        name: nginx
        kind: HelmRepository
        namespace: flux-system
      version: "0.15.1"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: nginx-system
data:
  values.yaml: |
    annotations:
      dapr.io/enabled: "true"
      dapr.io/app-id: nginx
      dapr.io/app-port: "80"
