---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: dapr
  chart:
    spec:
      chart: crossplane
      reconcileStrategy: ChartVersion
      sourceRef:
        name: crossplane-stable
        kind: HelmRepository
        namespace: flux-system
      version: "1.10.1"
  interval: 60m
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-aws
 namespace: crossplane-system
spec:
 package: xpkg.upbound.io/crossplane/provider-aws:v0.33.0