apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: load-balancer
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/load-balancer
  prune: true
  wait: true
  dependsOn:
  - name: metallb
