apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tekton
spec:
  releaseName: tekton
  chart:
    spec:
      chart: tekton-pipeline
      reconcileStrategy: ChartVersion
      sourceRef:
        name: tekton
        kind: HelmRepository
        namespace: flux-system
      version: "0.29.0"
  interval: 1m
  # valuesFrom:
  # - kind: ConfigMap
  #   name: tempo
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tempo
# data:
#   values.yaml: |
#     architecture: standalone