apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: petclinic
  namespace: petclinic
spec:
  sourceRef:
    kind: GitRepository
    name: petclinic
    namespace: petclinic
  interval: 10s
  prune: false
  path: ./flux
  targetNamespace: petclinic