apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: petclinic
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/petclinic
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system