apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cockroachdb
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/cockroachdb
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system