# --------------------------------------------------------------------------------------------------------------------------------------
# To understand the syntax of this patch, please consult https://fluxcd.io/flux/faq/#how-to-patch-coredns-and-other-pre-installed-addons
# --------------------------------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: kube-system 
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
    kustomize.toolkit.fluxcd.io/ssa: merge
    dapr.io/enabled: "true"
    dapr.io/app-id: traefik
    dapr.io/app-port: "80"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik

      
    