apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-patch
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  patches:
    - patch: |
        - op: add
          path: metadata/annotations
          value:
            dapr.io/enabled: "true"
            dapr.io/app-id: traefik
            dapr.io/app-port: "80"                
      target:
        kind: Service
        name: traefik
        namespace: kube-system