apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helm-sources
  namespace: flux-system
spec:
  interval: 10s
  path: ./infrastructure/helm-sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system