apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
spec:
  releaseName: nats
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        name: nats
        kind: HelmRepository
        namespace: flux-system
      version: "0.19.4"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: nats
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats
data:
  values.yaml: |
    auth:
      enabled: false
    jetstream:
      enabled: true