apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik-mesh
      reconcileStrategy: ChartVersion
      sourceRef:
        name: traefik
        kind: HelmRepository
        namespace: flux-system
      version: "4.1.1"
  interval: 1m
  # valuesFrom:
  # - kind: ConfigMap
  #   name: tempo
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tempo
# data:
#   values.yaml: |
#     architecture: standalone