apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        name: grafana
        kind: HelmRepository
        namespace: flux-system
      version: "6.44.8"
  interval: 1m
#   valuesFrom:
#     - kind: ConfigMap
#       name: grafana
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana
# data:
#   values.yaml: |
#     persistence:
#       enabled: false