apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-provisioner
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-provisioner
        namespace: provisioners
      interval: 1h
  values:
    replicaCount: 1
    strategyType: Recreate

    nfs:
      server: 192.168.10.4
      path: /mnt/pool0/kong
      mountOptions:
      - vers=3
      - nosuid

    storageClass:
      defaultClass: true
      provisionerName: nfs-provisioner
      name: nfs-storage
      reclaimPolicy: Delete
      archiveOnDelete: false
