apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        name: bitnami
        kind: HelmRepository
        namespace: flux-system
      version: "17.3.8"
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: redis
data:
  values.yaml: |
    replica:
      replicaCount: 0