apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: petclinic
  labels:
    app: petclinic
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: nginx
  rules:
  - host: petclinic.127.0.0.1.nip.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: owner-dapr
            port: 
              name: dapr-http