apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nats
spec:
  releaseName: petclinic
  interval: 5m0s
  chart:
    spec:
      chart: nats
      reconcileStrategy: ChartVersion
      sourceRef:
        name: nats
      version: "0.18.2"
  values: {}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nats
spec:
  interval: 60m
  url: https://nats-io.github.io/k8s/helm/charts/